@startuml B2BE Context
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

LAYOUT_WITH_LEGEND()
LAYOUT_AS_SKETCH()

Person(user, "Regular User ")

Person(admin, "Admin User")


Enterprise_Boundary(b2be, "B2BE") {
    System(wp3, "Web Portal",  "Include multi modules & allows users to manipulate the service that they bought")

    System(web_app_entry, "Application Entry", "used to dispatch messages between modules in WP3 or TDN") 

    System_Ext(tdn_server, "TDN", "EDI System")
}



System_Ext(erp_system, "ERP / SAP")



Rel_R(wp3, tdn_server, "send files", "shared mount")

Rel(admin, wp3, "Configure", "HTTP(S)")
Rel(user, wp3, "Uses", "HTTP(S)")


Rel(tdn_server, web_app_entry, "Push messages", "Database")
Rel(wp3, web_app_entry, "Push messages", "Database")
Rel(web_app_entry, wp3, "Call entry handler ", "Database")

Rel_R(tdn_server, erp_system, "deliver formatted output", "Email / Fax / ...")
@enduml